# Quizzzz โจทย์ฝึกท้ายบทเรียน

1.จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [1]:
import array as arr
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2.จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [33]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3.จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [35]:
x=np.random.rand(10,99,20)
x

array([[[0.17976824, 0.31555685, 0.07230597, ..., 0.99346889,
         0.40658682, 0.90914047],
        [0.89792581, 0.37059538, 0.92749482, ..., 0.50333506,
         0.01994285, 0.86054869],
        [0.84812458, 0.74546698, 0.50261575, ..., 0.06511726,
         0.09740236, 0.46347915],
        ...,
        [0.23563339, 0.28304021, 0.6808281 , ..., 0.66667803,
         0.27854146, 0.82267491],
        [0.04048488, 0.0489432 , 0.22430827, ..., 0.83460529,
         0.97777942, 0.141092  ],
        [0.38945357, 0.31007597, 0.22420354, ..., 0.25661746,
         0.93871498, 0.34979716]],

       [[0.94788931, 0.92872508, 0.72951641, ..., 0.11935168,
         0.82848709, 0.2020678 ],
        [0.01274411, 0.79099641, 0.853796  , ..., 0.25225251,
         0.29984899, 0.29634683],
        [0.37428109, 0.79615318, 0.8494799 , ..., 0.20817126,
         0.18044205, 0.91189813],
        ...,
        [0.17699246, 0.22294537, 0.71329191, ..., 0.43028167,
         0.6070897 , 0.45663946],
        [0.9

In [36]:
lst = x
#Map Lambha Function
result = map(lambda x:x**2,lst)
print(list(result))

[array([[3.23166203e-02, 9.95761266e-02, 5.22815339e-03, ...,
        9.86980439e-01, 1.65312841e-01, 8.26536393e-01],
       [8.06270768e-01, 1.37340932e-01, 8.60246648e-01, ...,
        2.53346178e-01, 3.97717152e-04, 7.40544055e-01],
       [7.19315302e-01, 5.55721019e-01, 2.52622593e-01, ...,
        4.24025780e-03, 9.48721985e-03, 2.14812926e-01],
       ...,
       [5.55230932e-02, 8.01117622e-02, 4.63526898e-01, ...,
        4.44459597e-01, 7.75853445e-02, 6.76794008e-01],
       [1.63902555e-03, 2.39543687e-03, 5.03142009e-02, ...,
        6.96565994e-01, 9.56052587e-01, 1.99069522e-02],
       [1.51674085e-01, 9.61471050e-02, 5.02672280e-02, ...,
        6.58525195e-02, 8.81185804e-01, 1.22358050e-01]]), array([[8.98494147e-01, 8.62530269e-01, 5.32194193e-01, ...,
        1.42448241e-02, 6.86390864e-01, 4.08313954e-02],
       [1.62412430e-04, 6.25675319e-01, 7.28967618e-01, ...,
        6.36313277e-02, 8.99094198e-02, 8.78214421e-02],
       [1.40086336e-01, 6.33859891e-01, 7

4.ทำเหมือนข้อ 3 แต่เขียนแบบ จงเขียน List comprehension  ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

5.นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [37]:
temp = np.arange(20)
import time
time1 = time.time()
x=temp**2
time2=time.time()
print(time2-time1)

0.0


In [38]:
import time
time1 = time.time()
[x**2 for x in range(20)]
time2 = time.time()
print(time2-time1)

0.0


6.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000

In [39]:
x=np.random.randint(10,1000,990)
print(x)

[130 717 227 676 898 942 506 515  40 495 684 493 622 610 144 834 214 137
  25 589 738 841 319 545  70 888 653 696 420 583 429 680 972 932 224 461
 356 504 842 719 192 803 669 620  43 626 253 791 139 475  94 751 344 592
 948 875 871 843 451 305  10  94 195 123 109 354 267 492  91 365 310 736
 965 330 266 807 704 634 951 872 771 456 243 636 778 711 588 484 582 696
  60 331 881 970 171 533 459 293 883 451 348 312 836 995 927 299 430 647
 723 648 738 529 545 993 847 314 381 161 940 828 744  97 241 725 843 578
 902 609 992 115 672 956 199 301 720 442 878 835 728 856 640 854 136 937
 869 291 713 259 654 725  30 871 565 690 864 868 555 487 977 206 981 365
 345 178 389 888 140  54 917 989 560 394 829  77  88 617 508  89 622 127
  93 288 464 612 792 243 962 297 615 404 795 466 395  79 779 174 652 337
 408 811 726 323 425 219 558 625 495 281 700 886 356 807 741 208 566 808
 773 153 589 485 611 774 809 212 828 653 153 258 381 769 415 472 413 734
 602 987 589 988 607 882 564 837 796 880 770  24 19

7.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000

In [40]:
a=np.random.randint(10,2000,1990)
a


array([1834,  364,  753, ...,  307,  608,  804])

In [41]:
a.sort()
a

array([  10,   13,   15, ..., 1997, 1999, 1999])

In [42]:
final_list = filter(lambda x: (x%2 ==0 ),a)
print(list(final_list))

[10, 16, 18, 22, 26, 30, 34, 44, 46, 46, 46, 50, 50, 52, 54, 64, 64, 64, 66, 66, 66, 66, 66, 70, 70, 70, 70, 74, 74, 78, 80, 82, 84, 84, 86, 88, 88, 90, 90, 90, 94, 98, 104, 104, 106, 112, 114, 114, 116, 118, 120, 124, 126, 126, 130, 132, 134, 134, 136, 136, 138, 140, 142, 144, 146, 148, 154, 154, 156, 158, 160, 162, 164, 164, 164, 170, 174, 176, 176, 180, 180, 182, 186, 188, 190, 196, 198, 198, 200, 200, 202, 204, 206, 208, 210, 210, 212, 212, 214, 216, 216, 218, 218, 220, 222, 222, 224, 226, 230, 232, 232, 234, 238, 238, 240, 240, 246, 252, 254, 256, 256, 256, 256, 258, 262, 262, 262, 266, 270, 270, 272, 272, 276, 276, 276, 280, 284, 284, 288, 290, 290, 292, 296, 298, 300, 304, 304, 304, 304, 304, 306, 306, 308, 308, 308, 308, 310, 310, 314, 316, 316, 316, 318, 324, 326, 332, 334, 334, 338, 338, 344, 344, 344, 346, 348, 350, 350, 350, 352, 354, 356, 356, 362, 364, 364, 368, 368, 368, 370, 370, 372, 374, 376, 376, 384, 384, 386, 386, 388, 400, 402, 406, 406, 410, 410, 412, 416, 418, 4

8.จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [43]:
a=np.random.randint(12,900,880)
a.sort()

final_list = filter(lambda x: (x%2 !=0 ),a)
print(list(final_list))

[15, 17, 21, 25, 25, 27, 27, 31, 31, 35, 35, 37, 41, 41, 43, 43, 43, 43, 49, 51, 59, 61, 67, 75, 77, 79, 81, 85, 85, 89, 89, 89, 93, 93, 95, 97, 103, 103, 103, 105, 111, 113, 113, 115, 115, 119, 119, 119, 123, 125, 125, 125, 127, 129, 131, 131, 135, 137, 139, 139, 143, 145, 147, 147, 149, 151, 151, 153, 157, 157, 157, 159, 163, 167, 167, 167, 173, 173, 173, 181, 181, 181, 185, 189, 191, 193, 199, 201, 203, 213, 213, 213, 215, 215, 217, 217, 223, 225, 225, 225, 229, 229, 229, 229, 229, 231, 233, 237, 245, 249, 249, 249, 251, 255, 259, 261, 263, 265, 267, 269, 269, 269, 271, 277, 279, 283, 287, 289, 291, 295, 299, 301, 301, 305, 309, 315, 317, 319, 323, 325, 325, 325, 327, 333, 335, 335, 337, 341, 343, 345, 347, 359, 359, 359, 361, 365, 367, 373, 375, 381, 381, 381, 381, 385, 393, 395, 403, 405, 405, 411, 411, 415, 417, 419, 425, 425, 425, 427, 427, 435, 435, 441, 441, 441, 443, 447, 449, 451, 451, 451, 457, 459, 459, 459, 463, 471, 471, 471, 473, 475, 475, 477, 479, 481, 485, 485, 491, 

9.จงสร้าง identity matrix แบบ 4x4

In [45]:
z=np.eye((4))
z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

10.จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [46]:
z=np.random.randint(5,25,100)
z

array([13, 24,  5, 24, 10, 20, 16,  9,  7,  7, 23, 11, 18, 23, 20, 20, 21,
        6, 20,  8, 11, 24, 15,  8, 10,  6, 24, 15,  6, 14, 12, 16, 20, 21,
       19,  6, 15, 19,  7,  8, 12, 16, 20, 14, 17, 14, 19, 13, 20, 18, 11,
       21, 21,  6, 16, 20, 19, 18, 14, 10,  5,  5, 21,  9, 13, 11, 15, 19,
       11, 23, 12, 12, 10,  8, 13,  9, 22, 19, 15, 23, 23, 16, 24, 17, 19,
       24, 22,  9,  6, 21, 12, 16,  5, 13, 10,  8,  6,  5,  9, 18])

11.จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [47]:
a=np.random.rand(1)
a

array([0.49760831])

12.จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [48]:
z=np.random.randint(50,100,(4,4))
z

array([[56, 71, 56, 94],
       [69, 75, 96, 97],
       [58, 85, 53, 80],
       [75, 57, 89, 56]])

In [49]:
ztranspose = z.transpose()
ztranspose

array([[56, 69, 58, 75],
       [71, 75, 85, 57],
       [56, 96, 53, 89],
       [94, 97, 80, 56]])

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [64]:
a=np.random.randint(1,20,1)
final_list = map(lambda x: (x!= 8,9,13,14),a)

print(list(final_list))

[(True, 9, 13, 14)]


14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [51]:
z=np.arange(1,26,1)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [52]:
z.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มี
ค่ามากกว่า 50 และปริ้นออกมา

In [71]:
z=np.random.randint(10,100,(5,5))
z

array([[78, 24, 67, 42, 96],
       [76, 99, 88, 13, 47],
       [98, 65, 10, 25, 22],
       [68, 39, 49, 39, 12],
       [70, 80, 29, 90, 43]])

In [72]:
z2 =(z**1 for x in z if x > 50 )
print(z2)

<generator object <genexpr> at 0x0000021842B55648>


In [73]:
final_list = filter(lambda x: (x>50),z)
z=np.array(final_list)
print(z)

In [56]:
z2= lambda x:x
print(z2(np.random.randint(10,100,(5,5))))

[[17 60 74 64 76]
 [15 79 79 80 67]
 [30 92 25 39 82]
 [40 92 88 72 18]
 [97 97 95 64 11]]


19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัว
ใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [57]:
x = np.random.randint(10,100,(5,5))
x

array([[61, 84, 98, 41, 70],
       [42, 38, 91, 85, 54],
       [76, 55, 44, 72, 90],
       [37, 36, 94, 15, 28],
       [42, 86, 86, 64, 89]])

20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมา
ทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [75]:
p1=[]
for i in range(9):
    number=int(input('input number 10-100: '))
    i += 1
    p1.append(number)
print(list(p1))    

input number 10-100: 88
input number 10-100: 33
input number 10-100: 44
input number 10-100: 54
input number 10-100: 15
input number 10-100: 65
input number 10-100: 94
input number 10-100: 53
input number 10-100: 56
[88, 33, 44, 54, 15, 65, 94, 53, 56]


In [76]:
p2=np.array(p1)
p3=p2.reshape(3,3)
p3

array([[88, 33, 44],
       [54, 15, 65],
       [94, 53, 56]])

In [77]:
ztranspose = p3.transpose()
ztranspose

array([[88, 54, 94],
       [33, 15, 53],
       [44, 65, 56]])